### ISSUE TITLE
Skid And pump Custom character Idles Will not Load but only move when the note Animations

### ISSUE THREAD

**Issue by Thefungang123** [TheDrawingCoder-Gamer/Funkin#1]
So the Idle will Never Apper No matte the xml. or Picture but Im Sure that Its the Json hope you can fix it

**Comment by TheDrawingCoder-Gamer** [comment]
This sounds like I borked the animation names again. I try to fix this soon!

**Comment by Thefungang123** [comment]
Oh thats Nice hope that you find a way to fix it Cuz this is an great Mod
