### ISSUE TITLE
Bug Report: Custom Characters crash the game when attempted to be used

### ISSUE THREAD

**Issue by prokube** [TheDrawingCoder-Gamer/Funkin#104]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

macOS
## What version of the game are you using? Look in the bottom left corner of the main menu.

0.2.7-mod-2.0.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

1. Make a custom character MANUALLY (add the files yourself into assets/custom_chars)
2. Use the character in a level
## Please describe your issue. Provide extensive detail and images if possible.

I figure all mentions of the character should be stated, so..

asset folder name + contents: custom_chars/icon/char.png, char.xml, icons.png.

json: custom_chars/icon.json

custom_chars.jsonc (whole file):
{
"icon": {
  "like": "dad",
  "icons": [26,27],
  "uniqueicons": true
  }
}

When I go into a level and change the enemy to "icon", the game crashes without any popup when i hit enter.

(are you proud of me for using the template correctly)

**Comment by MarioLuigi124** [comment]
why do you have a json for your custom characters? you don't need a json...

**Comment by TheDrawingCoder-Gamer** [comment]
wait what is this lol.

**Comment by prokube** [comment]
> also get rid of "uniqueicons: true"
yeah i followed that one old tutorial for 0.3 or whatever, im an idiot but i was desperate

> why do you have a json for your custom characters? you don't need a json...
what
why does every character have a json then
