### ISSUE TITLE
Bug Report: Cant exit out of menu in Song Select

### ISSUE THREAD

**Issue by XperiorTR** [TheDrawingCoder-Gamer/Funkin#107]
#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.
I checked.
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 64-bit not arm lol
## What version of the game are you using? Look in the bottom left corner of the main menu.
v.2.7.1-mod-2.1.0 (patch applied)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Options > New Week... > Select Songs 
## Please describe your issue. Provide extensive detail and images if possible.
I went into new week, select songs and i selected my song but couldnt exit the menu with backspace, i also tried esc, shift, space and ctrl.
also tring to make a stage crashes the game no matter what

**Comment by Happy2745** [comment]
It doesn't work for me either

**Comment by MarioLuigi124** [comment]
why are you using 2.1.0?

**Comment by TheDrawingCoder-Gamer** [comment]
fixed in 2.2.0
