### ISSUE TITLE
Bug Report: Setting a characters "like" value to "monster-christmas" then opening a song with that character will result in a crash.

### ISSUE THREAD

**Issue by XperiorTR** [TheDrawingCoder-Gamer/Funkin#108]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 10 Pro version 2004 64-bit
## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7.1-mod-2.1.0
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Setting a custom char's "like" value to "monster-christmas" then create a song with that character in it and play the song.
## Please describe your issue. Provide extensive detail and images if possible.
![Ekran görüntüsü 2021-03-15 112118](https://user-images.githubusercontent.com/80666310/111123589-965e4280-8580-11eb-8132-7828ce30f27e.png)
gives me this error

**Comment by CARCATGames** [comment]
@XperiorTR Try setting it the "like" value to "monster" or "newmonster". There doesn't seem to be a .json file for the Christmas Monster, that's why it's giving the error.

**Comment by XperiorTR** [comment]
I tried monster, character placement seemed off but i didnt try new monster imma check if it works.

**Comment by XperiorTR** [comment]
It worked! thanks
