### ISSUE TITLE
Enhancement: Stage Sounds

### ISSUE THREAD

**Issue by CARCATGames** [TheDrawingCoder-Gamer/Funkin#109]
There should a way to add in custom sounds to stages. Currently there doesn't seem to be a way to replace the vanilla game sounds used in stages like Philly, Limo, and Spooky without overriding that stage's sound file. (If I'm wrong about that please correct me). So basically, you should be able to put sound files for a stage in it's folder and have the game automatically detect them.

**Comment by MasterDirector99** [comment]
He's working on it soon...

**Comment by CARCATGames** [comment]
I saw on the Trello. However, I'm leaving it open until it's officially added.
