### ISSUE TITLE
Bug Report: HEY!

### ISSUE THREAD

**Issue by Thefungang123** [TheDrawingCoder-Gamer/Funkin#11]
Hey! the .exe file is Not there THIS IS REALLY IMPORTANT THE .EXE FILE IS NOT IN THE FILE WARNING WARNING IM GONNA SEND THIS MESSEGE TO GITHUB THIS IS AN EMERGANCY YOU NEED TO FIX THIS

**Comment by Thefungang123** [comment]
@TheDrawingCoder-Gamer PLS THIS MAKES IT UNUSABLE PLS

**Comment by Thefungang123** [comment]
@TheDrawingCoder-Gamer Pls you need to fix this this Will make the update not work PLS FOR THE LOVE OF GOD @TheDrawingCoder-Gamer  PLS! I SIMPLY ASK YOU TO FIX A SIMPLE ERROR THEN GO TO SLEEP BUT PLSSSS FIX IT

**Comment by TheDrawingCoder-Gamer** [comment]
lmao i suck at stuff haxelib run lime build windows acting up. you can get the file on github release page now https://github.com/TheDrawingCoder-Gamer/Funkin/releases/tag/v0.2.6-mod-0.3.0
