### ISSUE TITLE
Question: Could I chart a custom song, after adding it into FNF Modding Plus?

### ISSUE THREAD

**Issue by DJDogster1384** [TheDrawingCoder-Gamer/Funkin#111]
## What is your question?
I'm wanting to make a FNF song mod, and I have just finished the music, but I was wondering, is it possible that I could add the song into the game, and be able to make the song, without having to add the song back in every time?

**Comment by aloser123** [comment]
nah just chart it into the actual game first then port it in to modding+
it works 10x better

**Comment by prokube** [comment]
what i do is i map out the camera focuses in vanilla then i actually chart in modding+
