### ISSUE TITLE
mom.json

### ISSUE THREAD

**Issue by MarioLuigi124** [TheDrawingCoder-Gamer/Funkin#112]
singRIGHT has Mom Pose Left instead of Mom Pose right.... or add a mom-car.json

**Comment by Supporo** [comment]
I have expericed while making a character (not using modding) every character swaps left and right so I suggest that you put left note in right note and right note in left note. I hope this helps you!

**Comment by MarioLuigi124** [comment]
> I have expericed while making a character (not using modding) every character swaps left and right so I suggest that you put left note in right note and right note in left note. I hope this helps you!

left note goes to left note

**Comment by TheGoldenGuardian** [comment]
This is an issue in the vanilla game with how Mom's XML file is set up. She has no "Pose Right" because her "Pose Right" is just tagged in her files as "Pose Left" and "Left Pose" is used for left notes. It's weird.

**Comment by MarioLuigi124** [comment]
i think you are talking about momCar.xml

**Comment by TheGoldenGuardian** [comment]
> i think you are talking about momCar.xml. mom.xml has Pose Right

Both XMLs have "Pose Left" and "Left Pose" and completely lack "Pose Right"
I've checked in my local copy, a fresh Modding+ copy, and a fresh Vanilla copy.
I don't know what XML you have where she has anything tagged as Pose Right.

**Comment by MarioLuigi124** [comment]
it was from a mod...
