### ISSUE TITLE
Question: Why does it give me a error and crashes when I press finish? (while I was making a character)

### ISSUE THREAD

**Issue by rhylie124** [TheDrawingCoder-Gamer/Funkin#113]
## What is your question?
I'm confused, what does it mean?

**Comment by MarioLuigi124** [comment]
what was the error message?

**Comment by rhylie124** [comment]
oh wait, i did something wrong, i forgot to place some stuff that it gave me an error message and it crashed
(sorry for messaging late, i was sleeping)
