### ISSUE TITLE
Question: How to add custom dialog?

### ISSUE THREAD

**Issue by XperiorTR** [TheDrawingCoder-Gamer/Funkin#114]
I tried folowing the USER-README.txt but when i try to open it in FNF it softlocks like this:

![softlock](https://user-images.githubusercontent.com/80666310/111474453-247f2800-873d-11eb-978b-3cbe03ac4de8.png)

Am I doing something wrong or is this a bug?
On latest version btw

**Comment by XperiorTR** [comment]
oh i found what was wrong
im stupid

**Comment by XperiorTR** [comment]
Hmm i think i fixed all of my issues but it still softlocks

**Comment by XperiorTR** [comment]
when i set it to senpai it plays the dialog shows the portraits and plays the music but when i set it to my own it softlocks?

**Comment by XperiorTR** [comment]
it shows a haxe thing on the top i wonder if the program cant see something

**Comment by XperiorTR** [comment]
i give up

**Comment by MarioLuigi124** [comment]
portrait.png and portrait.xml in the custom characters folder and if you want custom dialog put the dialog like also the dialog must be the songnameDialog.txt not dialog.txt hopes this helps...
