### ISSUE TITLE
How to import mods made from FNFM+ to the vanilla FNF?

### ISSUE THREAD

**Issue by Hawkfire7751** [TheDrawingCoder-Gamer/Funkin#115]
I am not sure how to do this because I am a beginner. Help

**Comment by MasterDirector99** [comment]
Rename it to these original pngs and port it in FNF.

**Comment by MasterDirector99** [comment]
If you're looking for a compile, then i'm sorry.

**Comment by Hawkfire7751** [comment]
damn, i was wondering about a compile, but thanks anyways
