### ISSUE TITLE
Bug Report: Some error message of some sort

### ISSUE THREAD

**Issue by SonicFan214** [TheDrawingCoder-Gamer/Funkin#12]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

## Where are you playing the game?
On my desktop, downloaded.
### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
v.0.2.6
## Please describe your issue. Provide extensive detail and images if possible.
When I try to go to the menu where you can change characters I get an error message saying [lime.utils.Assets] ERROR: There is no TEXT asset with an ID of "assets/images/custom_chars/charlist.txt" ![image_2021-01-30_215717](https://user-images.githubusercontent.com/77948135/106374152-1ec4b300-6346-11eb-80f0-5026f70a32e7.png)

**Comment by TheDrawingCoder-Gamer** [comment]
Huh. I thought I had fixed this bug but it popped back up. Oops.

**Comment by TheDrawingCoder-Gamer** [comment]
In the project there is no reference to charlist.txt so I don't know why this happens.

**Comment by TheDrawingCoder-Gamer** [comment]
![Screenshot (16)](https://user-images.githubusercontent.com/26726264/106386621-db009680-63a3-11eb-9264-b26e7562ab2b.png)
Yeah no charlist in project. Make sure you've downloaded the latest version from the releases page. 
https://github.com/TheDrawingCoder-Gamer/Funkin/releases/tag/v0.2.6-mod-0.3.0

**Comment by SonicFan214** [comment]
ok, ill do that. I'm gonna see if that will work.

**Comment by SonicFan214** [comment]
yep that did it.
