### ISSUE TITLE
Bug Report: Trying to add a stage is only adding to my rage

### ISSUE THREAD

**Issue by DJDogster1384** [TheDrawingCoder-Gamer/Funkin#120]
I'm trying to port over the VS Annie mod to FNF Modding Plus, and I figured I should start with adding the BG/Stage that goes over Philly, when I add it, and select all the game files, 
![image](https://user-images.githubusercontent.com/74204727/111927783-47387600-8a88-11eb-9ff3-86395b1c734b.png)
This happens. And then the game crashes after hitting "Ok". When I tried adding a stage a while ago, only for it to not work, I figured "Oh, it must have been because those stages had some assets that were blank!" But seems like that's not it because VS Annie actually has every asset used in some way! Please help.

**Comment by MarioLuigi124** [comment]
what is the version?

**Comment by DJDogster1384** [comment]
2.1.2

**Comment by MarioLuigi124** [comment]
the latest version is 2.2.0 (you will have to add it without the game)

**Comment by DJDogster1384** [comment]
I've updated the game, and the options menu is gone. How am I going to do this now??

**Comment by DJDogster1384** [comment]
Update: I got the Atsuover stage in so I guess this is useless now???

**Comment by MarioLuigi124** [comment]
there is a patch version...
