### ISSUE TITLE
everytime i play a song it pops up with the message "JSON data on line 86: Unexpected end of data, expected ' " '." Bug Report: 

### ISSUE THREAD

**Issue by Dragonite727** [TheDrawingCoder-Gamer/Funkin#121]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
windows ('x86')
## What version of the game are you using? Look in the bottom left corner of the main menu.
2.2.0
## Please describe your issue. Provide extensive detail and images if possible.
[](url)

**Comment by MarioLuigi124** [comment]
on a normal song or a custom song? (also this have something to do with you doing something wrong...)

**Comment by Dragonite727** [comment]
> on a normal song or a custom song? (also this have something to do with you doing something wrong...)

normal

**Comment by MarioLuigi124** [comment]
what difficulty did you pick?

**Comment by Dragonite727** [comment]
> what difficulty did you pick?

i picked all of them and it kept doing it

**Comment by MarioLuigi124** [comment]
did you ever went to freeplaySongJson.jsonc?

**Comment by Dragonite727** [comment]
> did you ever went to freeplaySongJson.jsonc?

no

**Comment by Dragonite727** [comment]
> > did you ever went to freeplaySongJson.jsonc?
> 
> I FOUND OUT THE PROBLEM I DID SOMETHING WRONG WITH THE CHARACTERS{
> "template": {
> "like": "bf",
> "icons": [0,1]
> },
> "templateBfCar": {
> "like": "bf-car",
> "icons": [0,1]
> },
> "templateBfChristmas": {
> "like": "bf-christmas",
> "icons": [0,1]
> },
> "templateBfPixel": {
> "like": "bf-pixel",
> "icons": [0,1]
> },
> "templateDad": {
> "like": "dad",
> "icons": [0,1]
> },
> "templateGfCar": {
> "like": "gf-car",
> "icons": [0,1]
> },
> "templateGfPixel": {
> "like": "gf-pixel",
> "icons": [0,1]
> },
> "templateGf": {
> "like": "gf",
> "icons": [0,1]
> },
> "templateMonster": {
> "like": "monster",
> "icons": [0,1]
> },
> "templateNewMonster": {
> "like": "newmonster",
> "icons": [0,1]
> },
> "templateParents": {
> "like": "parents",
> "icons": [0,1]
> },
> "templatePico": {
> "like": "pico",
> "icons": [0,1]
> },
> "templateSenpaiAngry": {
> "like": "senpai-angry",
> "icons": [0,1]
> },
> "templateSenpai": {
> "like": "senpai",
> "icons": [0,1]
> },
> "templateSpirit": {
> "like": "bf-christmas",
> "icons": [0,1]
> },
> "templateSpooky": {
> "like": "spooky",
> "icons": [0,1]
> },
> "templateMom": {
> "like": "mom",
> "icons": [6,7]
> },
> "templateSenpai-hd": {
> "like": "senpai-hd",
> "icons": [22,22]
> },
> "templateSenpaiAngry-hd": {
> "like": "senpai-angry-hd",
> "icons": [22,22]
> },
> "templateSpirit-hd": {
> "like": "spirit-hd",
> "icons": [23,23]
> },
> "Trickmask" : {
> "like" Trickymask"
> "icons": [22,22]
> }

what did you think i did wrong?

**Comment by Dragonite727** [comment]
{
  "template": {
    "like": "bf",
    "icons": [0,1]
  },
  "templateBfCar": {
    "like": "bf-car",
    "icons": [0,1]
  },
  "templateBfChristmas": {
    "like": "bf-christmas",
    "icons": [0,1]
  },
  "templateBfPixel": {
    "like": "bf-pixel",
    "icons": [0,1]
  },
  "templateDad": {
    "like": "dad",
    "icons": [0,1]
  },
  "templateGfCar": {
    "like": "gf-car",
    "icons": [0,1]
  },
  "templateGfPixel": {
    "like": "gf-pixel",
    "icons": [0,1]
  },
  "templateGf": {
    "like": "gf",
    "icons": [0,1]
  },
  "templateMonster": {
    "like": "monster",
    "icons": [0,1]
  },
  "templateNewMonster": {
    "like": "newmonster",
    "icons": [0,1]
  },
  "templateParents": {
    "like": "parents",
    "icons": [0,1]
  },
  "templatePico": {
    "like": "pico",
    "icons": [0,1]
  },
  "templateSenpaiAngry": {
    "like": "senpai-angry",
    "icons": [0,1]
  },
  "templateSenpai": {
    "like": "senpai",
    "icons": [0,1]
  },
  "templateSpirit": {
    "like": "bf-christmas",
    "icons": [0,1]
  },
  "templateSpooky": {
    "like": "spooky",
    "icons": [0,1]
  },
  "templateMom": {
    "like": "mom",
    "icons": [6,7]
  },
  "templateSenpai-hd": {
    "like": "senpai-hd",
    "icons": [22,22]
  },
  "templateSenpaiAngry-hd": {
    "like": "senpai-angry-hd",
    "icons": [22,22]
  },
  "templateSpirit-hd": {
    "like": "spirit-hd",
    "icons": [23,23]
  },
  "Whitty" : {
  "like": "dad",
  "icons": [0,1]
  }
:      i changed more so whats wrong
