### ISSUE TITLE
Question: Adding Custom Modded Sprites

### ISSUE THREAD

**Issue by d0990** [TheDrawingCoder-Gamer/Funkin#122]
I wanted to know if u could add sprites such as tricky, whitty, miku and such

**Comment by MasterDirector99** [comment]
Make an JSON.

**Comment by d0990** [comment]
> Make an JSON.

Um i did and when i try to play with him he just crashes-

**Comment by prokube** [comment]
You shouldn't make a .json to accompany your custom character. Just put the png and the xml, perhaps the icons too, into your character's folder and then add an object to the jsonc that follows the pattern of the others.

**Comment by d0990** [comment]
> You shouldn't make a .json to accompany your custom character. Just put the png and the xml, perhaps the icons too, into your character's folder and then add an object to the jsonc that follows the pattern of the others.

How do I do that? and if you are able too, can you guide me?

**Comment by prokube** [comment]
https://github.com/TheDrawingCoder-Gamer/Funkin/issues/124 latest comment

**Comment by d0990** [comment]
> #124 latest comment

hes... there... but hew just stands there
no movemnt on notes or anything

**Comment by prokube** [comment]
update: you CAN make a json specifically for your character if you're compiling from source and want unique animations like Tankman's "ugh" sprite in the high-effort ugh mod. You just have to duplicate another json like dad.json and then do the stuff you wanna do.

Anyway, I've never had issues with still characters. Can you make sure your custom_chars.jsonc entry is listed as being based off the same character that your spritesheet is based off? The only thing I can think of is that Modding+ attributes the number of frames in an animation to the based-off character, so if the xml's number of frames doesn't match up with the game's number of frames, it does weird things.
