### ISSUE TITLE
whenever I start the game it says JSON Data on line 31: Unexpected end of file Expected this was my first time downloading it btw and i'm on MacBook and I can rub .exe files so this doesn't happen to me and im one the newest Version

### ISSUE THREAD

**Issue by prockscac** [TheDrawingCoder-Gamer/Funkin#123]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by MarioLuigi124** [comment]
did you just open it or did something in the files and jsons then open it?

**Comment by prockscac** [comment]
> did you just open it or did something in the files and jsons then open it?
I did something in the files I tried to add a new character and a week

**Comment by MarioLuigi124** [comment]
did you make a folder for the new character?

**Comment by prockscac** [comment]
oooooh that's why so I didn't make a folder for the new character cause I I never made  a new folder

**Comment by prockscac** [comment]
> did you make a folder for the new character? oooooh that's why so I didn't make a folder for the new character cause I I never made a new folder

**Comment by prockscac** [comment]
> did you make a folder for the new character?

im going to try that

**Comment by prokube** [comment]
lmao characters are broken on 2.0.1 but i really don't wanna migrate. also put your information in the LITERAL TEMPLATE instead of in the title
