### ISSUE TITLE
Enhancement: Include linux builds in github releases and on Gamebanana

### ISSUE THREAD

**Issue by DjBRINE** [TheDrawingCoder-Gamer/Funkin#125]
#### Please check for duplicates or similar issues before creating this issue.
I checked and found none
## What is your suggestion, and why should it be implemented?
You can add linux builds of your modification in github releases and gamebanana, so no linux users have to rely on wine.
I had recently successfully compiled the latest release on my Manjaro Linux machine. Works like a charm.
If you find it troubling to compile linux builds yourself, i can do it for you.

**Comment by TheDrawingCoder-Gamer** [comment]
Maybe, with azure pipelines. Will consider fixing azure pipeline build.

**Comment by TheDrawingCoder-Gamer** [comment]
Azure pipelines fucking absolutely breaks with linux/mac, so linux won't be avaliable any time in the near future. Sorry.
