### ISSUE TITLE
Question: how do i add custom icons?

### ISSUE THREAD

**Issue by asasassadfafa** [TheDrawingCoder-Gamer/Funkin#132]
## What is your question?
i tried the method on the user guide but no luck. what do it do

**Comment by prokube** [comment]
lmao the user guide is for some old update in the "1.-"s. Put all your custom char stuff into a new folder named after your character. rename the character png and xml to "char" then rename the custom icon grid to "icons". should be good from there

**Comment by ShamanCoder** [comment]
You also need to add your character into the D:\Soft\Games\Indie\FNFM+Win640.2.7.1-mod-2.2.0\assets\images\custom_chars\custom_chars.jsonc
