### ISSUE TITLE
Question: Changing stage or characters few times while playing a song

### ISSUE THREAD

**Issue by MuradNoob** [TheDrawingCoder-Gamer/Funkin#135]
just like the song called glitcher in Hex mod 
changing stage and characters few times while playing songs
what code should I put in the songs .json file
(if something you cant understand sorry for the bad English)

**Comment by prokube** [comment]
This feature isn't supported yet. I think it's in a category somewhere on the trello board, though

**Comment by MuradNoob** [comment]
welp that was too bad
