### ISSUE TITLE
Bug Report: Character unplayable

### ISSUE THREAD

**Issue by nickpythonluajava** [TheDrawingCoder-Gamer/Funkin#136]
im trying to import custom character tankman as pico, but when i select character tankman it crashes on me with no error messages
how do i fix this?

**Comment by MarioLuigi124** [comment]
playing as a custom pico crashes the game

**Comment by nickpythonluajava** [comment]
> playing as a custom pico crashes the game and you can't fix it...

that sucks darn

**Comment by BetaBits** [comment]
in the pico json the right note animation name is using bf's right animation name. just change it to this
![image](https://user-images.githubusercontent.com/79941305/114345022-ca903900-9b15-11eb-99d3-36b90e55b7e6.png)

**Comment by nickpythonluajava** [comment]
> in the pico json the right note animation name is using bf's right animation name. just change it to this and it should work
> ![image](https://user-images.githubusercontent.com/79941305/114345022-ca903900-9b15-11eb-99d3-36b90e55b7e6.png)

hmm it doesnt work, is the custom char supposed to have its own json?

**Comment by nickpythonluajava** [comment]
oh wait i didnt save
