### ISSUE TITLE
Bug Report: plays pico instead of my custom song (sorry i posted twice today)

### ISSUE THREAD

**Issue by nickpythonluajava** [TheDrawingCoder-Gamer/Funkin#138]
i made custom charts and got the inst and voices and put it into the freeplay thingy. when I enter the song it plays the chart but instead of playing my custom song it plays pico instead

i made a custom background for philly if that's the problem

**Comment by ShamanCoder** [comment]
You have to make sure you have set your custom song for the default difficulty. Hard and easy difficulties copy the song from the default difficulty, which is probably a bug.

**Comment by nickpythonluajava** [comment]
i fixed it, but not quite.
i went into debug menu and the song said it was listed as "pico" and instead when i type my custom song and my background it works.

however i still dont know how to fix this without going into debug menu

**Comment by bubsuki** [comment]
Open the chart (json) files for the song difficulties, cmd+f, and search for "pico". If it's there, replace it with the name of your custom song.

**Comment by nickpythonluajava** [comment]
> Open the chart (json) files for the song difficulties, cmd+f, and search for "pico". If it's there, replace it with the name of your custom song.

thanks will try
