### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by MrGamerDoesGames** [TheDrawingCoder-Gamer/Funkin#139]
## What is your question?
I'm trying to add a custom week image: eg. on story mode you scroll down and see week1, week2, week3, week4, week5, week6, and then week7. Only problem? I have no clue how to do that. Does anyone know how?

**Comment by ShamanCoder** [comment]
There is a section in the documentation about adding a custom week to the game: https://github.com/TheDrawingCoder-Gamer/Funkin/blob/master/USER-README.txt

**Comment by MrGamerDoesGames** [comment]
> There is a section in the documentation about adding a custom week to the game: https://github.com/TheDrawingCoder-Gamer/Funkin/blob/master/USER-README.txt

Thanks! While you're here, do you know how to do custom portraits? I tried and tried and couldn't get it to work.
