### ISSUE TITLE
Question: Where are the tutorial videos?

### ISSUE THREAD

**Issue by SonicFan214** [TheDrawingCoder-Gamer/Funkin#14]
# Please check for duplicates or similar issues before asking your question.

## What is your question?
Right now FNF Modding Plus is withheld and I need the tutorial videos so I can figure out how to add mods to FNF Modding Plus.

**Comment by SonicFan214** [comment]
I meant FNF Modding Plus is withheld on GameBanana.

**Comment by TheDrawingCoder-Gamer** [comment]
On my youtube channel, https://www.youtube.com/channel/UC9oJJwiPsRblfXhQQl9rGxQ

**Comment by SonicFan214** [comment]
thank you!
