### ISSUE TITLE
Question: How to do custom portraits

### ISSUE THREAD

**Issue by MrGamerDoesGames** [TheDrawingCoder-Gamer/Funkin#141]
Maybe I'm just stupid, but I can't for the life of me get portraits to work. I tried and tried again, and couldn't. Could someone please help me?

**Comment by MarioLuigi124** [comment]
you put the portrait flies in your custom characters folder (for example the folder will be called bf.png) then you need to rename the portrait files to portrait. then it should load the portrait.

**Comment by MrGamerDoesGames** [comment]
> you put the portrait flies in your custom characters folder (for example the folder will be called bf.png) then you need to rename the portrait files to portrait. then it should load the portrait.

I tried this and the portraits just didn't appear. I'll try it again though. Thanks.

**Comment by MarioLuigi124** [comment]
you know the folder of your custom character

**Comment by MrGamerDoesGames** [comment]
> you know the folder of your custom character

Yes I do know. Say my characters name is Aidan. Do i name it portrait or aidanPortrait?

**Comment by MrGamerDoesGames** [comment]
> you put the portrait flies in your custom characters folder (for example the folder will be called bf.png) then you need to rename the portrait files to portrait. then it should load the portrait.

I tried and it didn't work -_-

**Comment by MarioLuigi124** [comment]
no just portrait

**Comment by prokube** [comment]
portrait.png, portrait.xml. you also have to go into the xml and rename the image path to portrait.png, i believe.
