### ISSUE TITLE
Bug Report: Missing When Hitting Notes

### ISSUE THREAD

**Issue by Happy2745** [TheDrawingCoder-Gamer/Funkin#142]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)
## What version of the game are you using? Look in the bottom left corner of the main menu.
2.2.0
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No.
## Please describe your issue. Provide extensive detail and images if possible.
When I'm playing a custom chart And hit a note it will sometimes make me miss even if I get it perfect.

**Comment by BetaBits** [comment]
yeah this happens a lot with some mods a like to play and it usually happens when trying to hit a note before or slightly after finishing a long note. im currently trying to see if its possible to put kade engine's input system into modding plus so this little issue can stop pissing me off

**Comment by christianfirecup** [comment]
> yeah this happens a lot with some mods a like to play and it usually happens when trying to hit a note before or slightly after finishing a long note. im currently trying to see if its possible to put kade engine's input system into modding plus so this little issue can stop pissing me off

have you gotten anywhere with this jw

**Comment by MrGenie151** [comment]
> > yeah this happens a lot with some mods a like to play and it usually happens when trying to hit a note before or slightly after finishing a long note. im currently trying to see if its possible to put kade engine's input system into modding plus so this little issue can stop pissing me off
> 
> have you gotten anywhere with this jw

kade's engine is open soruce, he could try changing the input via dowloading the modding+ source and kades engine and finding the haxe files that control the controls for both engines and replace modding+'s one with kades.

**Comment by TheDrawingCoder-Gamer** [comment]
2.2.0 old version, bugs considered >:(
