### ISSUE TITLE
Question: How does one add Dialogue?

### ISSUE THREAD

**Issue by Salted-Beef** [TheDrawingCoder-Gamer/Funkin#143]
I've made a dialog.txt file in one of the song folders (pico) But it doesn't work. I've tried to rename it to picoDialog.txt, but that doesn't seem to help either. The debug menu doesn't really show anything regarding dialogue or cutscenes, so im not really sure what to do right now. Help would be appreciated. Thanks in advance!

Edit: aight so i did a thing, so now it plays the dialogue cutscene, but no dialogue shows up and the game freezes.
I don't really know how to explain it but i put something like this in the debug menu's first tab

gf | pico
bf | Philly
none | pico

**Comment by MarioLuigi124** [comment]
why did you change the ui to none?

**Comment by Salted-Beef** [comment]
the ui was like that when i went into debug, changing pico to senpai just played senpai's dialogue as opposed to the custom pico dialogue

**Comment by Djw1213** [comment]
Move the dialoge.txt  to the level your created in the data folder for example one of my levels is named funky beats go into that folder and place the dialoge.txt. Rename the dialoge.txt to dialog.txt. Go into your level and press 7 and in the box that says none write plainDialog or for a pixel level write pixelDialog. Write them both how I wrote it here. Let me know if this helps.
