### ISSUE TITLE
Enhancement: I was wondering if you could make a Mac version?

### ISSUE THREAD

**Issue by DarkMinerULTRA** [TheDrawingCoder-Gamer/Funkin#144]
Sorry if it's too much to ask, but I'd really love a Mac version so Mac users like me don't have to buy a whole new computer just to make a mod. Thanks!

**Comment by DarkMinerULTRA** [comment]
Wait crap you can use on mac shit

**Comment by prokube** [comment]
1. Bootcamp
2. Wine
3. Literally compile the source

Also reminder to close the issue

**Comment by DarkMinerULTRA** [comment]
Alright, thanks!
________________________________
