### ISSUE TITLE
Question: How Does One Add A Icon To A Custom Character?

### ISSUE THREAD

**Issue by o-gui-blindao** [TheDrawingCoder-Gamer/Funkin#145]
## What is your question?
I Wanted To Add A Custom Character But I Can't Figure out how to add the icon, how do i do that?

**Comment by prokube** [comment]
add the icongrid to your character's folder, and rename the icongrid to icons.png. if you didn't make a folder, and actually followed the readme exactly, make the folder and name it after your character.

**Comment by o-gui-blindao** [comment]
nvm i did it
