### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by BlueShelledCardbord** [TheDrawingCoder-Gamer/Funkin#151]
Im trying to add a character, but I get this message:

![Error 4_20_2021 11_14_36 AM](https://user-images.githubusercontent.com/82896918/115430727-3afc2180-a1ca-11eb-8dac-05cfb8ebc7db.png)

**Comment by glichex114** [comment]
add the character xml file
For example
BOYFRIEND.png
BOYFRIEND.xml
if your character does not have one use the xml of the character your character is going over

**Comment by BlueShelledCardbord** [comment]
I already have an xml file for the png in the same folder

**Comment by glichex114** [comment]
how did you add the character by the mod menu in game or through files

**Comment by BlueShelledCardbord** [comment]
Through the files

**Comment by MarioLuigi124** [comment]
does the char.xml and char.png exist?

**Comment by MarioLuigi124** [comment]
also is it added in this file? custom_chars.jsonc
