### ISSUE TITLE
Question: How do add mod characters to fnf plus?

### ISSUE THREAD

**Issue by Djw1213** [TheDrawingCoder-Gamer/Funkin#152]
I'm trying to add mod characters to fnf plus like the characters from the x event, sky, tord and etc but when i do that it just crashes the game. I created a json for them but it crashes. Or i had it ware i added a character but there's a problem of floating or taking up the whole screen its werid. Does certain mod character need to use a certain json? I've mostly using lemon demon's and the dad's but most with no luck. The only character I was able to get to work was marbabe and i don't know why it isn't working for the others. I feel like i'm so close to figuring it out but I need a little guidance.
![Screenshot (49)](https://user-images.githubusercontent.com/82912742/115471373-7bc15e00-a1fd-11eb-883b-e8899bfeb084.png)
![Screenshot (50)](https://user-images.githubusercontent.com/82912742/115471376-7c59f480-a1fd-11eb-85af-828fd53d8849.png)

**Comment by prokube** [comment]
vase is just being stupid, idk how to fix size

with ink!, you need to modify the "enemyOffset" in the character's json. if ink doesn't have his own custom json to be based off of, give him one. Example:

![Screen Shot 2021-04-26 at 4 32 21 PM](https://user-images.githubusercontent.com/68293280/116163784-46a98580-a6ad-11eb-9dab-a2f64a36ed95.png)
![Screen Shot 2021-04-26 at 4 32 33 PM](https://user-images.githubusercontent.com/68293280/116163790-47421c00-a6ad-11eb-97d5-f292654629c8.png)
![Screen Shot 2021-04-26 at 4 32 40 PM](https://user-images.githubusercontent.com/68293280/116163791-47dab280-a6ad-11eb-87d5-ef149ecfc210.png)


Keep in mind that a higher second value will result in a lower position.

**Comment by Djw1213** [comment]
Oh i didn't think anyone would respond. That's interesting I will have to try that ive been changing all the values in dividually for example idle, up etc to fix him. I kind of fixed him but if this works better I will do this instead. Also it alright about vase it kinda sucks I can't change his size hopefully i can find someone to help me with that but thank you.
