### ISSUE TITLE
Question: Game is looking for file that wasn't explained in the guide

### ISSUE THREAD

**Issue by BobTheNerd10** [TheDrawingCoder-Gamer/Funkin#156]
So I'm trying to add tord to the game, but this always pops up, there is no guide for this
![image](https://user-images.githubusercontent.com/48499877/115949173-f43b4f80-a487-11eb-8925-119b3d953d10.png)
How do I make the file?

**Comment by ShamanCoder** [comment]
It would be nice if you shared how you fixed the error here to help others avoid such error in the future

**Comment by MarioLuigi124** [comment]
why is it like tord?

**Comment by BobTheNerd10** [comment]
1, I didn't fix it, I gave up
2, It was a test because the tord mod is somewhat simple, I gave up when tordbot was under the floor
