### ISSUE TITLE
Question: How do add a new ui to the game?

### ISSUE THREAD

**Issue by Djw1213** [TheDrawingCoder-Gamer/Funkin#161]
Im trying to figure out how to add different ui's to the game but they just keep crashing when I load into the level. One example of what i'm trying to do is most thorn characters have a cutscene before the battle but because it has to do with the ui i can't change it for my custom levels. Also tried adding the ui from the corruption mod and it crashes as well. There is no error message that appears so I don't know what the cause could be. If anyone can help with this that would be great.

**Comment by MarioLuigi124** [comment]
uitypes.txt

**Comment by MarioLuigi124** [comment]
uitypes.txt is in data

**Comment by Djw1213** [comment]
Thank you that helped I had no idea that is where you would add it there.
