### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by FidgetSpinnersAnimations** [TheDrawingCoder-Gamer/Funkin#163]
When I select my template character using the char select, it works, but when I leave and reopen the song, it goes back to the original one. edit: i put them in reverse order edit #2: when i save it it changes back
![issue pictur 3](https://user-images.githubusercontent.com/83421082/116590890-e0f30e80-a8e3-11eb-85ed-25b601536dd8.png)
![issue pictur 2](https://user-images.githubusercontent.com/83421082/116590891-e18ba500-a8e3-11eb-894c-a242b7ccabe6.png)
![issue pictur 1](https://user-images.githubusercontent.com/83421082/116590893-e18ba500-a8e3-11eb-9a99-218fb4a9f61c.png)

**Comment by MarioLuigi124** [comment]
that's not a bug

**Comment by MarioLuigi124** [comment]
add the custom character in the json if you don't want the game to change the character back

**Comment by Djw1213** [comment]
You have to add what you want to the json press 7 add the character, while still in the debug menu press the song icon and cilck on the save icon. It will show your desktop. For example ill say im trying to edit a song called brightside. For the character to be on all versions of your json go on easy add the character, press save and name it brightside-easy, and but it in the data folder, do the same thing for normal and hard by saying brightside and brightside-hard. Let me know if this helps.

**Comment by FidgetSpinnersAnimations** [comment]
oh i forgot to mention, it changes back even when i save it

**Comment by FidgetSpinnersAnimations** [comment]
nevermind i fixed it
