### ISSUE TITLE
Question: how do i fix this?

### ISSUE THREAD

**Issue by myst-rblx** [TheDrawingCoder-Gamer/Funkin#168]
## What is your question?
soo basically I was trying to test my mod and I got this error and thought "alright no biggie I'm just gonna do haxelib install tjson" and it didn't work (I also tried using command prompt to run haxelib install tjson and that didn't work either) and now I'm wondering how do I fix it? 
![image](https://user-images.githubusercontent.com/76845277/117539979-472b1000-b00d-11eb-820a-c4c036d33c92.png)
edit: nevermind just had to run command prompt as an administrator

**Comment by IAmAHumanToo** [comment]
TheDrawingCoder-Gamer is literally CLOSING THE F-ING QUESTION WITHOUT ANSWERING
