### ISSUE TITLE
modding plus for 32-bit windows pc

### ISSUE THREAD

**Issue by JustSingelModder** [TheDrawingCoder-Gamer/Funkin#174]
I have a 32-bit pc and i want to make mod but it's not working pls make this for 32-bit windows

**Comment by TheDrawingCoder-Gamer** [comment]
Will check to see if pipelines supports it. Todo.

**Comment by TheDrawingCoder-Gamer** [comment]
3115340af2d2bf6da775c5cb17a1c73a4a382f44 fixes this
