### ISSUE TITLE
Bug Report: Game Freezes After Selecting Freeplay Song.

### ISSUE THREAD

**Issue by NewFriskFan26** [TheDrawingCoder-Gamer/Funkin#180]
So, the game just freezes whenever I try to select the very song I'm trying to add. Help?
Computer (or laptop in this case info) ((also also don't worry fnf runs at 120 fps so that's not the problem)):
OS: Windows 7 Pro
Made By: DELL
Processor: Intel (R) Core(TM) i5-6200u CPU @ 2.30GHz, 2401 MHz, 2 hearts, 4 processors...
Friday Night Funkin: Latest
Modding Plus: Latest (not patch-vers)
I made sure to follow everything step by step, so what's up?

**Comment by TheDrawingCoder-Gamer** [comment]
latest is not helpful

**Comment by IAmAHumanToo** [comment]
dude what the **crap** TheDrawingCoder-Gamer you didn't even help.
