### ISSUE TITLE
Custom stages not working

### ISSUE THREAD

**Issue by awesome6048** [TheDrawingCoder-Gamer/Funkin#181]
Custom stages not working.

OS: Windows 10 x64.

Version: 2.2.0.

Manually add a custom stage.

When I go to manually add a custom stage to the game (following all of the steps in the readme and yt video), then I go to a song in the game and change the stage to my custom stage, there is no stage. All there is instead of a stage is blackness behind the characters.

Also, the readme is very outdated.

**Comment by MarioLuigi124** [comment]
the json in custom stage folder when you open it you press enter or copy and paste an existing line and add the comma to the line before the line you created or copied (example:
  "templateSchool": "school",
  "custom stage folder name here": "what the custom stage is like") put in the name of the folder for the custom stage,then put in what it's like. or you spelled it wrong...

**Comment by kurtmoney** [comment]
No OP is right, it just doesn't work properly and any video you can find is outdated, as is the Read Me
