### ISSUE TITLE
Enhancement: a Pre-compile the latest version of this mod

### ISSUE THREAD

**Issue by SansGamer17** [TheDrawingCoder-Gamer/Funkin#184]
I really like this mod and I use it a lot, and I wanted to use the latest version of the mod, but I don't have enough open space to compile the whole thing myself, so I wanted to ask you if you may compile the latest version and put it up for download so I and probably many others could enjoy it without having to compile it with every update.

**Comment by SansGamer17** [comment]
oops, didn't see you did it already, sorry

**Comment by SansGamer17** [comment]
oh, there isn't the latest version yet, I should really look closer when doing stuff like this

**Comment by TheDrawingCoder-Gamer** [comment]
it does exist
