### ISSUE TITLE
Enhancement: kade engine modchart support if it isnt in already

### ISSUE THREAD

**Issue by arceuss** [TheDrawingCoder-Gamer/Funkin#185]
im trying to get my soulless 4 modchart over to modding+ but the lua that centers the players side and hides everything else doesnt seem to work

**Comment by TheDrawingCoder-Gamer** [comment]
lua isn't supported but hscript is. will consider reimplementing lua

**Comment by TheDrawingCoder-Gamer** [comment]
lua stinky pee pee poo poo

**Comment by arceuss** [comment]
> lua stinky pee pee poo poo

?

**Comment by FuseIsHere813** [comment]
it means lua sucks, which does suck
