### ISSUE TITLE
Bug Report: whenever i load in the character the whole game just crashes idk why but at least the character shows up in the list :D

### ISSUE THREAD

**Issue by MisterHolts** [TheDrawingCoder-Gamer/Funkin#186]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by windows10win7posreadywoeskio** [comment]
??????

**Comment by TheDrawingCoder-Gamer** [comment]
unhelpful
