### ISSUE TITLE
Bug Report:  Tutorial error message

### ISSUE THREAD

**Issue by SonicFan214** [TheDrawingCoder-Gamer/Funkin#19]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

## Where are you playing the game?
Downloaded in a folder with the location of Downloads\My Folder\Fangames\Friday N⁬ight Funkin' (I think it may have some formatting like bold but I'm not sure)
### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.6
## Please describe your issue. Provide extensive detail and images if possible.
I went to the tutorial stage and then went to debug menu and got this error message.
![image_2021-01-31_121844](https://user-images.githubusercontent.com/77948135/106393737-769f0080-63be-11eb-83b8-75bee47b17a2.png)

**Comment by TheDrawingCoder-Gamer** [comment]
The commit fcf92a7c4c326cbe8022fc62d96bb8c627cacd5d solves this, and will be in the next update.
