### ISSUE TITLE
Adding a custom stage doesn't work.

### ISSUE THREAD

**Issue by kurtmoney** [TheDrawingCoder-Gamer/Funkin#191]
The README document tells you how to do it in a way that isn't possible anymore, as does every video I've seen. Regardless, I read and watched what I could, and when finally changing the name of the stage to what I made my custom folder, a black screen is used as the stage instead. 

I even tried using the "add custom stage" in the options while in game and that doesn't do anything either.

And yes, I did do everything with the JSON as instructed by the mod itself.

**Comment by Sanic9999** [comment]
Do you have your stuff like this?
![image](https://user-images.githubusercontent.com/85415242/121113259-5a312b80-c7d7-11eb-83fd-cd14c712fa34.png)
![image](https://user-images.githubusercontent.com/85415242/121113287-661ced80-c7d7-11eb-9a63-ae655ab9b0d7.png)
![image](https://user-images.githubusercontent.com/85415242/121113304-6d43fb80-c7d7-11eb-8ff3-bb7356b72871.png)

**Comment by kurtmoney** [comment]
I have it exactly like this in the files, but if i put it like stage, then it just makes it the normal stage, and if I make it original, it is black.

**Comment by Sanic9999** [comment]
What is your stage replacing?

**Comment by kurtmoney** [comment]
It's completely original, like modding plus is _supposed_ to let you make.

**Comment by Sanic9999** [comment]
Sorry, I can't really help with that then cause all of the custom stages I've imported I used base game stages as a base.

**Comment by kurtmoney** [comment]
Yea I tried to do that with the normal dad stage, but when I put it as “like stage” it just uses the normal stage and not the new stuff I put in the new folder
