### ISSUE TITLE
Bug Report:  Note Splash Lag

### ISSUE THREAD

**Issue by gamerbross** [TheDrawingCoder-Gamer/Funkin#197]
![image](https://user-images.githubusercontent.com/55158797/121427250-ca28e880-c974-11eb-9556-32b575442861.png)
that code makes some note splash lag, the code would be better like that, because it works as in the original game
![image](https://user-images.githubusercontent.com/55158797/121427429-ff353b00-c974-11eb-901a-508f8ea78d43.png)

**Comment by TheDrawingCoder-Gamer** [comment]
??? these are basically the same code? that's just an artifact of compiling to javascript
