### ISSUE TITLE
Bug Report: Week 6 text on story mode incorrect

### ISSUE THREAD

**Issue by keanu64github** [TheDrawingCoder-Gamer/Funkin#207]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
v4.0.0
## Please describe your issue. Provide extensive detail and images if possible.
Week 6 text says "maowling" not "moawling"

**Comment by TheDrawingCoder-Gamer** [comment]
:grief:

**Comment by TheDrawingCoder-Gamer** [comment]
47beaf4727db1cb8700c19a93be5fae6b453da24
