### ISSUE TITLE
Question: How do you edit positions of characters on stages?

### ISSUE THREAD

**Issue by RebatemanYT** [TheDrawingCoder-Gamer/Funkin#209]
Was wondering how you would modify let's say Stage to work for a let's say Skid & Pump mirror match (made a char that uses the two as a base). Also would it modify for all songs if I were to do it on one song?

**Comment by RebatemanYT** [comment]
Also before anyone asks, yes I know about the 8 key, but idk how to swap to BF with it. Maybe tho we could use an enhanced editor... (also idk how to add a label)

**Comment by TheDrawingCoder-Gamer** [comment]
I- How- did you ask a question when i removed that option :grief:
please ask this on our https://discord.gg/96nV4Q5HMr or the discussions tab
