### ISSUE TITLE
Bug Report: Bobeepo and Dadbattle crash the game upon entering them in free play.

### ISSUE THREAD

**Issue by REZHub396** [TheDrawingCoder-Gamer/Funkin#217]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
I am using Windows (x86_64).
## What version of the game are you using? Look in the bottom left corner of the main menu.
I am using version 4.0.0-947425012 (weekly3)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Enter free play.
2. Select either Bobeepo or Dadbattle.
## Please describe your issue. Provide extensive detail and images if possible.
Whenever I attempt to play either Bobeepo or Dadbattle on any difficulty, the game gives the error: "[file_contents,assets/images/custom_dialogs/dialogBoxes/normal.json]" and crashes the game.
I have attached a screenshot below. I was wondering how this issue could be fixed.
![Screenshot (8)](https://user-images.githubusercontent.com/59940450/123198294-b182fd00-d461-11eb-8aa5-594453cb5184.png)

**Comment by SpookLad** [comment]
It will also do this with any song with dialog from older versions, a temporary solution is simply removing the dialog file.

**Comment by REZHub396** [comment]
Alright, I'll give that a try. Thank you for letting me know.
