### ISSUE TITLE
Held note lines disappear at the beginning  

### ISSUE THREAD

**Issue by BTABray** [TheDrawingCoder-Gamer/Funkin#219]
### First of all,
If you do not understand what I mean, because I don't know how to word it correctly, here's a video of me playing Satin Panties because that song has tons of held notes. (i had to compress the video)

https://user-images.githubusercontent.com/84481384/123442082-248f8f00-d59a-11eb-88ce-961d6612a631.mp4

![a2](https://user-images.githubusercontent.com/84481384/123441962-0d50a180-d59a-11eb-8f75-66c11be97a6f.jpg)

**Comment by MasterDirector99** [comment]
This was fixed in the later builds.
