### ISSUE TITLE
Bug Report: Dialog with new update Is softlocked/broken

### ISSUE THREAD

**Issue by TrafficKid** [TheDrawingCoder-Gamer/Funkin#226]
![image](https://user-images.githubusercontent.com/84630346/124021298-65800d00-d9b9-11eb-87a8-6db47170170c.png)
The new dialog Is broken and doesn't work for the latest update which was supposed to fix them :) Just wanted to let you know

**Comment by TheDrawingCoder-Gamer** [comment]
this error message looks like it didn't find a character definition. 

likely user error : )

**Comment by TrafficKid** [comment]
I'm confident It's a bug, There's no reason It shouldn't work I've looked over It many times

And just copy and pasting the week 6 dialog files don't work either
