### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Charizardslash** [TheDrawingCoder-Gamer/Funkin#27]
Skins over Mom don't work and crash the game. (The christmas parents skins don't work either but that's understandable.)

**Comment by TheDrawingCoder-Gamer** [comment]
Unsure why this would happen. Will look into it.

**Comment by JackoCatacomb** [comment]
Why am i getting this error? All i did was add a character over pico!
![proof](https://user-images.githubusercontent.com/78385598/106520444-6d875f80-64a2-11eb-830d-42cd24fd5dec.PNG)

**Comment by TheDrawingCoder-Gamer** [comment]
These kinds of errors usually mean a json is messed up. Make sure your custom_chars.json is properly formed.
Json reference: https://www.json.org/json-en.html

**Comment by JackoCatacomb** [comment]
and you have fixed my depression

**Comment by Arthur-pootis** [comment]
> These kinds of errors usually mean a json is messed up. Make sure your custom_chars.json is properly formed.
> Json reference: https://www.json.org/json-en.html

i dont understand the reference :(

**Comment by Bandanadee0** [comment]
After a certain amount of custom characters are added the select a character screen on the "7" menu it goes up instead of down. I don't know if this is an issue with the game or the mod.
![Screenshot (16)](https://user-images.githubusercontent.com/67713374/106741388-99f9c380-65e9-11eb-8da0-4cb3610ba4f4.png)

**Comment by Arthur-pootis** [comment]
> After a certain amount of custom characters are added the select a character screen on the "7" menu it goes up instead of down. I don't know if this is an issue with the game or the mod.
> ![Screenshot (16)](https://user-images.githubusercontent.com/67713374/106741388-99f9c380-65e9-11eb-8da0-4cb3610ba4f4.png)

it may be from both
either the game can't support that many or the mod isn't ready for a certain number
try removing template, as he's useless

**Comment by TheDrawingCoder-Gamer** [comment]
I don't know why the game would do this. I assume this would happen because of the engine. I will look at it.

**Comment by TheDrawingCoder-Gamer** [comment]
Also please seperate your issues. I am going to close this issue because the main problem is going to be fixed.
