### ISSUE TITLE
Bug Report: Custom girlfriends are mirrored

### ISSUE THREAD

**Issue by MiyakuKage** [TheDrawingCoder-Gamer/Funkin#29]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [x] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.6-mod-0.3.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Just by adding a custom character like: gf
## Please describe your issue. Provide extensive detail and images if possible.
Custom girlfriends (That you either play against or are just in the background), are reversed (they face the wrong direction) for some unknown reasons 
![image](https://user-images.githubusercontent.com/78387925/106526642-45215480-64e6-11eb-8160-29acfa306845.png)
![image](https://user-images.githubusercontent.com/78387925/106526707-608c5f80-64e6-11eb-8b52-92daf6eed4b6.png)

**Comment by TheDrawingCoder-Gamer** [comment]
The commit cd0c0dcc48a235ab30273d94dd85065d8a306a1f solves this, and will be in the next update.
