### ISSUE TITLE
Question: Is there a way to add custom Weeks?

### ISSUE THREAD

**Issue by Thefungang123** [TheDrawingCoder-Gamer/Funkin#3]
Is custom weeks posible Cuz if custom Stages are possible Maybe custom weeks are possible

**Comment by TheDrawingCoder-Gamer** [comment]
Custom weeks were added but crash the game. I am getting around to fixing it.

**Comment by Thefungang123** [comment]
Oh! Thats really great! Cuz ive been doing an Mod and now im Using this mod Cuz it can now give me a lot Of creative liberty now Like "Side Story weeks" Like "Ralsei skid and Pump Adventure trough Minecraft" I know that sounds stupid but i can In the futur Do that with this Mod right?

**Comment by TheDrawingCoder-Gamer** [comment]
8a1bbb143d74811866275a46dddfe22acca4c644 closes this
