### ISSUE TITLE
Bug Report: Boyfriend Week 6 problem

### ISSUE THREAD

**Issue by MasterDirector99** [TheDrawingCoder-Gamer/Funkin#35]
There was an issue where bf-pixel were resetting their animations too early and were briefly in their idle animation.

There's also an issue where in Week 6, BF's Game Over Screen is setted to default.

**Comment by TheDrawingCoder-Gamer** [comment]
The commit 6f1dec3e53f0d91ade5fc613e43b57c242203504 solves this, and will be in the next update.
