### ISSUE TITLE
Bug Report: Custom spooky boys do not properly animate as of latest release

### ISSUE THREAD

**Issue by bitch-boy** [TheDrawingCoder-Gamer/Funkin#37]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [X ] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7-mod-0.4.0
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Creating a custom character that is like spooky, followed by simply copying their assets and XML file. Enter a song using such a custom character to see the issue.
## Please describe your issue. Provide extensive detail and images if possible.
The idle animation used by the spooky boys is broken - they will restart the idle animation sooner than normal - cutting it off in a jarring and unusual manner. To be clear, this only occurs with custom spooky-like characters. The existing spooky boys do not have this issue.

**Comment by TheDrawingCoder-Gamer** [comment]
The commit 1a4a344be2dda5ce2201efdc93885ed492f94e47 solves this, and will be in the next update.
