### ISSUE TITLE
Bug Report: Skid 'n Pump? More like Skid 'n Shut the f*ck up

### ISSUE THREAD

**Issue by DJDogster1384** [TheDrawingCoder-Gamer/Funkin#39]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)
None

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:
None
### Local
- [ ] Windows x86
- [Insert check mark ] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
I'm using the most recent version 0.41

## Please describe your issue. Provide extensive detail and images if possibe.
"SpookyMinus": {
    "like": "spooky",
    "icons": [0,1]
    "uniqueicons": false
![image](https://user-images.githubusercontent.com/74204727/107081586-eea36700-67c0-11eb-856a-b3f5761ad21c.png)

**Comment by MarioLuigi124** [comment]
i came to help you take away "uniqueicons": false

**Comment by DJDogster1384** [comment]
> i here to help you. all you need to do is get rid of "uniqueicons": false. that's the problem.

Thanks! I could have sworn I tried that, but I had also messed something else up, so I guess you were right! Thanks!

**Comment by TheDrawingCoder-Gamer** [comment]
Yeah this is just invalid json, you forgot the comma
