### ISSUE TITLE
Revert menu to old menu

### ISSUE THREAD

**Issue by Thefungang123** [TheDrawingCoder-Gamer/Funkin#4]
# Please check for duplicates or similar issues before asking your question.

**Comment by Thefungang123** [comment]
also i preffer it related to the Picture Insted of text Cuz Text Makes it complicated 
![campaign_menu_UI_assets](https://user-images.githubusercontent.com/78193874/106348229-abae3480-6292-11eb-8433-63a53c887b9f.png) Also wanted to use that sooo....

**Comment by Thefungang123** [comment]
And now that i think about it ATLEAST Keep the pictures cuz that can give creativity insted of "An specific Font" Better?

**Comment by Thefungang123** [comment]
So pls can you tell me would you put the pictures back with 3 Template weeks or something similar like that?

**Comment by TheDrawingCoder-Gamer** [comment]
I suck at graphic design so unless someone can make a week icon I don't want to do this. Later down the line I maybe will allow one to use custom graphics but now that is not possible.

**Comment by Thefungang123** [comment]
Ok How you can Make it work with graphics but at the same time Custom week Dont either work for An strange reason and i dont know why :/

**Comment by TheDrawingCoder-Gamer** [comment]
did you download version 0.2.6-mod-0.2.1 because the game crashes on version 0.2.6-mod-0.2.0

**Comment by Thefungang123** [comment]
Well im trying in fnfmoddingpluswin64_1a4c2

**Comment by TheDrawingCoder-Gamer** [comment]
current version is 191fb

**Comment by Thefungang123** [comment]
Ah i see
Time to dowload and pass the files to The new version for the FIFTH TIME

**Comment by TheDrawingCoder-Gamer** [comment]
sorry i make sloppy stuff then fix it.

**Comment by Thefungang123** [comment]
I know
its just its A Lil irritating

**Comment by Thefungang123** [comment]
not gonna lie

**Comment by Thefungang123** [comment]
So umm yeah custom stages there a lil Not a lot of creative options

**Comment by Thefungang123** [comment]
Well its only stage soo yeah

**Comment by TheDrawingCoder-Gamer** [comment]
well I will work on that later I am working on week characters rn

**Comment by Thefungang123** [comment]
an what does that mean?

**Comment by Thefungang123** [comment]
Just asking

**Comment by TheDrawingCoder-Gamer** [comment]
Custom characters display on top of story menu and then probably custom week icons

**Comment by Thefungang123** [comment]
![image](https://user-images.githubusercontent.com/78193874/106363988-ded7de80-62f9-11eb-80a8-9b7df8d2b76b.png)
Oh boi yep weeks crash the game all right

**Comment by Thefungang123** [comment]
Ah wait the , Maybe thats the problom

**Comment by TheDrawingCoder-Gamer** [comment]
yeah json kinda strict

**Comment by Thefungang123** [comment]
Ok new problom It did load

**Comment by Thefungang123** [comment]
But the dificulty thing does not Apper

**Comment by TheDrawingCoder-Gamer** [comment]
ik but it is still there idk why i will fix it

**Comment by Thefungang123** [comment]
Thats great to Hear!

**Comment by TheDrawingCoder-Gamer** [comment]
0b9015a4e6c155e48e3f278d384abc77e0ffb86c closes this
