### ISSUE TITLE
Bug Report: Custom car girlfriends do not properly animate as of latest commit at time of writing

### ISSUE THREAD

**Issue by bitch-boy** [TheDrawingCoder-Gamer/Funkin#40]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [X] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7-mod-1.0.0 (commit 08ab8a2c4a07ff0c80813212c56f7b49ee0d5073 built from source)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Create a custom character that is like gf-car (B-Side's gf-car recolor as an example, but you could just copy the default) and set a song to be using this gf.
## Please describe your issue. Provide extensive detail and images if possibe.
gf-car like characters do not animate properly - remaining stuck on the first frame at all times. The speaker she sits on also overlaps things it should not. non-car custom gfs also have issues in the Philly stage when a train passes by.

**Comment by TheDrawingCoder-Gamer** [comment]
v1.0.0 fixes this
