### ISSUE TITLE
Bug Report: Camera placement with custom senpai 

### ISSUE THREAD

**Issue by MiyakuKage** [TheDrawingCoder-Gamer/Funkin#43]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [x] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Put a custom senpai as your enemy in the school stage
## Please describe your issue. Provide extensive detail and images if possibe.
I tried with the recently released Monika and the senpai template, and the camera just isnt at the right place when it's their time to sing (It works well with regular senpai)
![image](https://user-images.githubusercontent.com/78387925/107146228-06a4f300-6947-11eb-9f8e-e141dbaa32d1.png)

**Comment by TheDrawingCoder-Gamer** [comment]
On the most recent update this _should_ be fixed
