### ISSUE TITLE
Enhancement: Skip song settings menu

### ISSUE THREAD

**Issue by MiyakuKage** [TheDrawingCoder-Gamer/Funkin#48]
# Please check for duplicates or similar issues before creating this issue.

## What is your suggestion, and why should it be implemented?
Maybe a setting to disable the new menu before selecting a song or a week? (With the full combo, snake notes and all). I, and I hope other people, would like to go directly to a song without having to go through that, thank you if you do, and if you don't, still thank you because this mod is amazing

**Comment by TheDrawingCoder-Gamer** [comment]
This was initially in the game in the 1.0.0 prototype but was removed. Will consider adding it back.

**Comment by TheDrawingCoder-Gamer** [comment]
The commit f5278a95a5c461749f4386037de0c9f93dec96fa solves this, and will be in the next update.
