### ISSUE TITLE
Bug Report: Custom UI slowdown

### ISSUE THREAD

**Issue by MasterDirector99** [TheDrawingCoder-Gamer/Funkin#51]
Every time I add a custom UI, it keeps having slowdown, can you fix this problem?

**Comment by TheDrawingCoder-Gamer** [comment]
This is a known issue. Will try and solve this.

**Comment by TheDrawingCoder-Gamer** [comment]
e9252a29cf03690c0520b82ede66cba04bdffa2d _should_ fix this and will be in next update
