### ISSUE TITLE
Bug Report: Skins over gfCar crash the game

### ISSUE THREAD

**Issue by Arthur-pootis** [TheDrawingCoder-Gamer/Funkin#52]
I tried this with the bad apple gf and since its over gfCar idk if i should put gf or gfCar, if you're supposed to put gfCar, please let me know

**Comment by TheDrawingCoder-Gamer** [comment]
Gf car is one the gf that has blowing hair while normal gf has many sprites like frightened and such. If you were to put a normal gf over gf car the game would crash as it tries to access non existant animations.

**Comment by Arthur-pootis** [comment]
Sorry, i didnt update
