### ISSUE TITLE
Bug Report: Adding a week name in storySonglist.json crashes the game

### ISSUE THREAD

**Issue by Bandanadee0** [TheDrawingCoder-Gamer/Funkin#56]
If you add a week name into storySonglist.json the game crashes.
No extra week name:
![image](https://user-images.githubusercontent.com/67713374/107717562-ea37ec00-6ca1-11eb-86bf-4cc8319578a4.png)
Extra week name:
![image](https://user-images.githubusercontent.com/67713374/107717532-d2f8fe80-6ca1-11eb-9c43-7afa05ef058b.png)

**Comment by Bandanadee0** [comment]
![image](https://user-images.githubusercontent.com/67713374/107718144-3fc0c880-6ca3-11eb-8c9e-7f325dd77de2.png)
Would also like to add what storySonglist.json looked like when adding the extra week name.

**Comment by TheDrawingCoder-Gamer** [comment]
You are missing a comma on `"hating simulator ft. maowling"` The game crashes because it expected either the end of the array or a comma.
