### ISSUE TITLE
Question: how do i compile on macos???

### ISSUE THREAD

**Issue by midosgithub** [TheDrawingCoder-Gamer/Funkin#58]
![Screenshot 2021-02-12 at 4 22 55 AM](https://user-images.githubusercontent.com/78944504/107726712-fb0c5000-6ce9-11eb-9b68-95f35ea48520.png)
when i compile on mac thats what i get (which shows me that the app is probably not gonna run)
and after i try to run it i get this 
![Screenshot 2021-02-12 at 4 23 37 AM](https://user-images.githubusercontent.com/78944504/107726766-14ad9780-6cea-11eb-8acc-4bb95817e2c2.png)
anyone able to help??? 
(i used the lime test mac -debug thing to compile it)

**Comment by TheDrawingCoder-Gamer** [comment]
check this out https://lime.software/docs/advanced-setup/macos/ also try running "lime test neko" this will make the game a little buggy but it will launch without you having to install stuff

**Comment by prokube** [comment]
Answer: Don't. Use Wine and Wineskin. :)
