### ISSUE TITLE
Custom Week Character

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [TheDrawingCoder-Gamer/Funkin#6]
## What is your suggestion, and why should it be implemented?
Add custom week character support

**Comment by Thefungang123** [comment]
Do a similar treatment with the Character.json and make it follow the same line of the character idle then try to Load idk if it works its just an idea i got in my Mind

**Comment by TheDrawingCoder-Gamer** [comment]
0b9015a4e6c155e48e3f278d384abc77e0ffb86c closes this
