### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by That0neMime** [TheDrawingCoder-Gamer/Funkin#60]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows 64x
## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7-mod-0.4.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
It happens all the time.

## Please describe your issue. Provide extensive detail and images if possible.

https://user-images.githubusercontent.com/76805857/107832474-c03c0380-6d4d-11eb-9a56-bd6530c0460b.mp4
![image](https://user-images.githubusercontent.com/76805857/107832532-dd70d200-6d4d-11eb-881d-067f85920996.png)

**Comment by MarioLuigi124** [comment]
the newer versions doesn't use jsons for custom characters anymore... you just need to add the custom character files name here.png name here.xml and then you just need to add the custom character's name that you put in the files in custom_chars.json
{
  "name here": {
    "like": "bf",
    "icons": [0,1]
  },
then you are done...... i never used a json for a custom character........ only in custom_chars.json..................................
