### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by TheGameBoyz** [TheDrawingCoder-Gamer/Funkin#63]
### If you are playing a downloaded version of the game, what operating system are you using?
64bit windows
## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7-mod-1.0.0
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

Yes, every time I select a certain song on hard, it chooses normal anyway.

## Please describe your issue. Provide extensive detail and images if possible.

When I load a song up in hard, it switches to normal.
(Video Example: https://cdn.discordapp.com/attachments/717496267919589507/811319154250481684/2021-02-16_20-28-31.mp4 )

**Comment by TheDrawingCoder-Gamer** [comment]
This means it couldn't find the proper json file. To avoid crashing, the game defaults to normal.
