### ISSUE TITLE
Enhancement: "High Quality" dialogue portraits

### ISSUE THREAD

**Issue by MiyakuKage** [TheDrawingCoder-Gamer/Funkin#64]
## What is your suggestion, and why should it be implemented?
My suggestion is to add a way to have non pixelated portrait icons (Like In Friday Night Funkin restored mod for exemple)
That would make the custom cutscenes more good looking and more accessible to make to everyone

**Comment by MasterDirector99** [comment]
It looks like they're working on it right now!

**Comment by TheDrawingCoder-Gamer** [comment]
added
