### ISSUE TITLE
Can someone tell me what's wrong with my code? When I select story mode, it crashes.

### ISSUE THREAD

**Issue by LeonJackaman** [TheDrawingCoder-Gamer/Funkin#69]
{
  "songs": [
    ["tutorial selected","Tutorial"],
    ["WEEK1 select", "Bopeebo", "Fresh","Dadbattle"],
    ["week2 select", "Spookeez", "South"],
    ["Week 3 press", "Pico", "Philly", "Blammed"],
    ["Week 4 press", "Satin-Panties", "High", "Milf"],
    ["week 5", "Cocoa", "Eggnog", "Winter-Horrorland"],
    ["Week 6", "Senpai", "Roses", "Thorns"],
    ["Week 6", "Play-with-Fire", "Cradles"]
  ],
  "weekNames": [
    "",
    "Daddy Dearest",
    "Spooky Month",
    "PICO",
    "MOMMY MUST MURDER",
    "RED SNOW",
    "hating simulator ft. moawling"
    "Unhuman"
  ],
  "characters": [
    ["dad", "bf", "gf"],
    ["dad", "bf", "gf"],
    ["spooky", "bf", "gf"],
    ["pico", "bf", "gf"],
    ["mom", "bf", "gf"],
    ["parents-christmas", "bf", "gf"],
    ["senpai", "bf", "gf"],
    ["narak", "bf", "gf"]
  ]
}

**Comment by LeonJackaman** [comment]
also nice, ticket number is... nice.

**Comment by LeonJackaman** [comment]
The mod overall is done, I just need to import it into a week and uh, yeah.

**Comment by family1242** [comment]
I've been having the same problem.

**Comment by MarioLuigi124** [comment]
week6 
week6?
idk the problem... week 6 already exist?...

**Comment by MarioLuigi124** [comment]
found the problem...
"weekNames": [
"",
"Daddy Dearest",
"Spooky Month",
"PICO",
"MOMMY MUST MURDER",
"RED SNOW",
"hating simulator ft. moawling"
"Unhuman"
],
this what you need to do add a comma after "hating simulator ft. moawling" and it shoud look like this
"weekNames": [
"",
"Daddy Dearest",
"Spooky Month",
"PICO",
"MOMMY MUST MURDER",
"RED SNOW",
"hating simulator ft. moawling",
"Unhuman"
],
hope this helps
