### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by DJDogster1384** [TheDrawingCoder-Gamer/Funkin#7]
I'm playing the most recent version of the mod, and I used Chrome to download the mod, when I try to go into Debug Mode on Tutorial, THIS happens.
![image](https://user-images.githubusercontent.com/74204727/106365648-ea7cd280-6304-11eb-9a36-cec347070df5.png)

**Comment by TheDrawingCoder-Gamer** [comment]
The game doesn't handle songs w/o voices that well so this is what happens. Will fix next update.

**Comment by TheDrawingCoder-Gamer** [comment]
This looks like this was a known problem for the base game, thus doesn't affect this mod. Please check if the issue is on the original project and ask there.
