### ISSUE TITLE
New update RUINS Custom Characters

### ISSUE THREAD

**Issue by DJDogster1384** [TheDrawingCoder-Gamer/Funkin#70]
I'm on windows. This new update has made it so if you load a Custom Character, the game immediatley crashes. PLEASE help

**Comment by MarioLuigi124** [comment]
what version are you using? 2.0.0 or 2.0.1

**Comment by DJDogster1384** [comment]
> what version are you using? 2.0.0 or 2.0.1 and what's the error message?

The most recent version and it's patch, and there is no error message, it just closes

**Comment by Bandanadee0** [comment]
> > what version are you using? 2.0.0 or 2.0.1 and what's the error message?
> 
> The most recent version and it's patch, and there is no error message, it just closes

You might have to A: Put all the character files for 1 character into a folder and name the folder the equivalent of what it is in the custom_chars.jsonc file and then name the character char.png  the xml to char.xml the icons icons.png the dead sprite (pixel bf only) to dead.png the thorns cutscene (spirit only) to crazy.png and crazy.xml and the txt file (spirit only) to char.txt, B: If you already have the folder with the characters name just name the files the names above, or C: you didn't type in the right things into custom_chars.jsonc. I can also provide visuals if you need it and I might be wrong on somethings

**Comment by MarioLuigi124** [comment]
...i use the game to put in custom characters...

**Comment by Bandanadee0** [comment]
Actually after looking at it you probably just typed it in wrong

**Comment by d0990** [comment]
I have this same problem too

**Comment by DJDogster1384** [comment]
> > > what version are you using? 2.0.0 or 2.0.1 and what's the error message?
> > 
> > 
> > The most recent version and it's patch, and there is no error message, it just closes
> 
> You might have to A: Put all the character files for 1 character into a folder and name the folder the equivalent of what it is in the custom_chars.jsonc file and then name the character char.png the xml to char.xml the icons icons.png the dead sprite (pixel bf only) to dead.png the thorns cutscene (spirit only) to crazy.png and crazy.xml and the txt file (spirit only) to char.txt, B: If you already have the folder with the characters name just name the files the names above, or C: you didn't type in the right things into custom_chars.jsonc. I can also provide visuals if you need it and I might be wrong on somethings

Yeeeeaaaaah, doesn't work. The game still closes

**Comment by Bandanadee0** [comment]
> > > > what version are you using? 2.0.0 or 2.0.1 and what's the error message?
> > > 
> > > 
> > > The most recent version and it's patch, and there is no error message, it just closes
> > 
> > 
> > You might have to A: Put all the character files for 1 character into a folder and name the folder the equivalent of what it is in the custom_chars.jsonc file and then name the character char.png the xml to char.xml the icons icons.png the dead sprite (pixel bf only) to dead.png the thorns cutscene (spirit only) to crazy.png and crazy.xml and the txt file (spirit only) to char.txt, B: If you already have the folder with the characters name just name the files the names above, or C: you didn't type in the right things into custom_chars.jsonc. I can also provide visuals if you need it and I might be wrong on somethings
> 
> Yeeeeaaaaah, doesn't work. The game still closes

Im just gonna make visuals and use enabf as an example
![image](https://user-images.githubusercontent.com/67713374/108629854-e50c3700-742f-11eb-8f02-7ecf0ae6e622.png)
This is what the folder should look like
![image](https://user-images.githubusercontent.com/67713374/108629888-0a994080-7430-11eb-8285-4709bff77138.png)
And this is what the jsonc should look like
If it just crashes when you load it it probably means you typed it in wrong. Im pretty sure you can't use numbers or symbols in the name either.

**Comment by DJDogster1384** [comment]
Do you think the problem could be how I don't have every character in folders?

**Comment by Bandanadee0** [comment]
> Do you think the problem could be how I don't have every character in folders?

Probably

**Comment by DJDogster1384** [comment]
![image](https://user-images.githubusercontent.com/74204727/108631004-d032a200-7435-11eb-9869-f009bfc97a76.png)
Should I delete all the stuff down here?

**Comment by Bandanadee0** [comment]
> ![image](https://user-images.githubusercontent.com/74204727/108631004-d032a200-7435-11eb-9869-f009bfc97a76.png)
> Should I delete all the stuff down here?

No. Those hold the animations for the custom characters

**Comment by DJDogster1384** [comment]
Those PNG files?

**Comment by DJDogster1384** [comment]
Damn, it STILL crashes the game

**Comment by DJDogster1384** [comment]
So, do I delete those template PNG files that aren't in their own folder??

**Comment by Bandanadee0** [comment]
Yeah those are fine to delete.

**Comment by DJDogster1384** [comment]
This isn't working still, it's just not. Either on my end I messed up, or this update broke the game
![image](https://user-images.githubusercontent.com/74204727/108631556-78496a80-7438-11eb-92bf-4412079566a0.png)
![image](https://user-images.githubusercontent.com/74204727/108631570-87c8b380-7438-11eb-9a4d-eaa864310c0d.png)

**Comment by Bandanadee0** [comment]
> This isn't working still, it's just not. Either on my end I messed up, or this update broke the game
> ![image](https://user-images.githubusercontent.com/74204727/108631556-78496a80-7438-11eb-92bf-4412079566a0.png)
> ![image](https://user-images.githubusercontent.com/74204727/108631570-87c8b380-7438-11eb-9a4d-eaa864310c0d.png)

I think I found the problem: You can't have capital letters in the name. I tried it out by copying a already existing character and just renaming so it has a capital letter and it crashed without a warning

**Comment by Bandanadee0** [comment]
Also i'd like to point out that gf-christmas and mom-car aren't supported yet so if you ever use mods that go over them they won't work.

**Comment by DJDogster1384** [comment]
It's not working, I renamed ALL of them in the text files, and their folders to have lowercase names 
![image](https://user-images.githubusercontent.com/74204727/108632234-d7f54500-743b-11eb-9052-8776bc09b9a3.png)
![image](https://user-images.githubusercontent.com/74204727/108632247-eb081500-743b-11eb-86e0-7abf1fef96a5.png)

**Comment by Bandanadee0** [comment]
It might also be caused by "uniqueicons": false not being under the icons text in the jsonc. (And change the false to true if you want the custom icons to show up). Other than that I can't think of anything else being wrong.

**Comment by DJDogster1384** [comment]
Not working, I think the update and patch broke the game

**Comment by DJDogster1384** [comment]
Oh yeah, and the songs I add don't show up, either, and if the custom characters don't work, the song I added will certainly not work

**Comment by Bandanadee0** [comment]
It could also be a problem with the song if you edited the json to add them in so you don't have to type it in every time.

**Comment by Bandanadee0** [comment]
> Not working, I think the update and patch broke the game

Im on the newest update and patch and mine work

**Comment by Bandanadee0** [comment]
Lets get into custom songs then, im gonna be using shiver as an example.
![image](https://user-images.githubusercontent.com/67713374/108632801-c6fa0300-743e-11eb-8b3d-e6cc35bec1cd.png)
This is what the folder should look like
![image](https://user-images.githubusercontent.com/67713374/108632815-d7aa7900-743e-11eb-80e7-252125694208.png)
The name should be changed to the name of the folder but with uppercase letters.
![image](https://user-images.githubusercontent.com/67713374/108632851-ff99dc80-743e-11eb-88a4-53577a01cde7.png)
This is what freeplaySongJson.jsonc should look like
![image](https://user-images.githubusercontent.com/67713374/108632899-3a037980-743f-11eb-8d6e-a69dcdd6134b.png)
And this is what music should look like.
The folder name should be lowercase and same with the file names along with the name inside the folder being uppercase and being the same as the music file names.
Also if you added  "uniqueicons": false there should be a comma after the icons they go over.

**Comment by MarioLuigi124** [comment]
"uniqueicons": false doesn't work with the newer versions...

and i use the game to add custom characters...

**Comment by Bandanadee0** [comment]
> "uniqueicons": false doesn't work with the newer versions...
> 
> (i use the game to add custom characters...)

I just use the files and have been since version 0.2.6

**Comment by d0990** [comment]
I just use custom characters at all. I don't know why though. I've tried everything but nothing works

**Comment by Bandanadee0** [comment]
> I just use custom characters at all. I don't know why though. I've tried everything but nothing works

Yeah its confusing at times although I do like the more user friendlier option of just adding them in game.

**Comment by DJDogster1384** [comment]
YOO I FINALLY FIGURED IT OUT! Man, it was DEFINITLEY not easy to figure out, but I did! And I have Bandanadee0 to thank! I didn't realize that there was an option to add custom characters, and using some thinking, I got it to work! Thank you, Bandanadee0! I wouldn't have figured this out without your help!
