### ISSUE TITLE
I can't modify the camera values in the .json files??

### ISSUE THREAD

**Issue by That0neMime** [TheDrawingCoder-Gamer/Funkin#71]
when I modify the "camOffsetX" value in the dad.json file, nothing happens the camera stays the same.
I tried everything. I restarted the song, I restarted the game. Nothing happened.

**Comment by TheDrawingCoder-Gamer** [comment]
there are two things, followCam and camOffset, followCam now affects the character iirc and camOffset affects cutscenes
