### ISSUE TITLE
everytime i try to load a character in my custom song, it crashes

### ISSUE THREAD

**Issue by d0990** [TheDrawingCoder-Gamer/Funkin#73]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by d0990** [comment]
I am using a windows 64 and every time i try to load the song with the custom character, it has an error message saying its missing .xml files when its already there

**Comment by d0990** [comment]
No more error message, but now it just crashes

**Comment by MarioLuigi124** [comment]
but which version? 1.0.0,2.0.0,2.0.1,or older

**Comment by d0990** [comment]
> but which version? 1.0.0,2.0.0,2.0.1,or older

2.0.0

**Comment by MarioLuigi124** [comment]
did you went to the debug menu? if you did,did you type in the name correctly?
