### ISSUE TITLE
Bug Report: Playing as any custom Pico crashes the game

### ISSUE THREAD

**Issue by MiyakuKage** [TheDrawingCoder-Gamer/Funkin#79]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)
## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7-mod-2.0.0
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Make a custom pico (like: "pico" in the custom chars jsonc file)
## Please describe your issue. Provide extensive detail and images if possible.
The characters work while playing against them, but now while playing as em (And I cant figure out a way to fix this myself since it crashes without any error message, just like if the character didnt exist.)

**Comment by MarioLuigi124** [comment]
i don't know how to fix this...

**Comment by MiyakuKage** [comment]
> i don't know how to help with this...

It's okay dont worry, I just was letting you know
Also, playing against a custom bf crashes the game as well

**Comment by MarioLuigi124** [comment]
> > i don't know how to help with this...
> 
> It's okay dont worry, I just was letting you know
> Also, playing against a custom bf crashes the game as well

it doesn't crash for me when i play against a custom bf...
