### ISSUE TITLE
Bug Report: Custom bf death screens are put upward and sometimes clip

### ISSUE THREAD

**Issue by Bandanadee0** [TheDrawingCoder-Gamer/Funkin#80]
Normal:
![Screenshot (18)](https://user-images.githubusercontent.com/67713374/109401980-329d0e00-7920-11eb-8f1e-73cd13809d98.png)
Custom bf that is a recolor:
![Screenshot (20)](https://user-images.githubusercontent.com/67713374/109401990-3f216680-7920-11eb-90be-c94ed546985b.png)
Custom bf that isn't a recolor:
![Screenshot (19)](https://user-images.githubusercontent.com/67713374/109401995-46e10b00-7920-11eb-96f7-5e6b28814ab1.png)

**Comment by MarioLuigi124** [comment]
.xml?

**Comment by Bandanadee0** [comment]
> .xml?
Here's what it looks like with a custom xml
![image](https://user-images.githubusercontent.com/67713374/109489112-67aa7d00-7a54-11eb-9890-e3f022bfbe1d.png)

**Comment by MarioLuigi124** [comment]
the top is cut off... ok...

**Comment by MarioLuigi124** [comment]
what version is this? 1.0.0,2.0.0,or 2.0.1?

**Comment by Bandanadee0** [comment]
> what version is this? 1.0.0,2.0.0,or 2.0.1?

2.0.1 I'll redownload the file and test it, if it's fixed then I'll close the issue.

**Comment by MarioLuigi124** [comment]
ok...

**Comment by TheDrawingCoder-Gamer** [comment]
old version >:(
