### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by edgardeivis** [TheDrawingCoder-Gamer/Funkin#81]
Hey!, did i do something wrong?, i did all the things the readme told me to do to add a custom song, i don't know why it's not working i named the folder "live-and-learn" the json files i got from the pico song and renamed them to "live-and-learn" ,"live-and-learn-hard","live-and-learn-easy", then i added the music "Live-And-Learn_Inst" , and "Live-And-Learn_Voices"
 i did all the things you asked me to do, why isn't it working?, the music doesn't play

**Comment by MarioLuigi124** [comment]
you didn't edit the .json files (live-and-learn.json,live-and-learn-hard.json,and live-and-learn-easy.json)
![image](https://user-images.githubusercontent.com/78293838/109447043-d239c980-7a10-11eb-9d0f-555155d236f1.png)
try to find song if you find or find next (on notepad) put in song and press find next 2 times and replace it with the song Live-And-Learn and freeplaysonglist.txt or freeplaysongjson.jsonc will need the folder name for the song being live-and-learn
hope this helps
