### ISSUE TITLE
Question: Custom Week image placement

### ISSUE THREAD

**Issue by ExoticMudkipz** [TheDrawingCoder-Gamer/Funkin#82]
So I'm creating my own custom week, and so far, everything works perfectly. Songs appear how they should, as well as mapping and the bonus week appears as well. Only problem with it is that the image I created for it saying "BONUS WEEK" doesn't appear correctly, and instead only shows the word "EASY" off the image, no matter how much I edit the XML. 
![Screenshot 2021-03-01 140043](https://user-images.githubusercontent.com/79869392/109545207-8e89a300-7a96-11eb-9055-d370d953f5c4.png) 
![week7](https://user-images.githubusercontent.com/79869392/109545315-b842ca00-7a96-11eb-80d7-da63084df39f.png)

Any way I can fix this? I copied one of the base game XMLs btw, if that helps anyone

**Comment by MarioLuigi124** [comment]
...i think it need to exist in the xml...

**Comment by ExoticMudkipz** [comment]
> ...i think it need to exist in the xml...

As I've stated, I added a new instance in the week7.xml, but no matter where I put the coordinates of it, it only shows up as "easy". Kind of a glaring flaw. If I were to duplicate a XML of say, week6.xml, name it week7.xml, what would I have to add into it in order for my bonus week graphic to show up?

**Comment by MarioLuigi124** [comment]
i don't i have the same problem...

**Comment by ExoticMudkipz** [comment]
I Found out the issue. The extra week xml in the custom ui will only use the first line that it sees, which was "EASY". Just mess with the coordinates and size with trail and error and you'll get it eventually to the point where it'll only show your custom week graphic.
