### ISSUE TITLE
Question: Disable Modifiers and Victory screen to look like base game?

### ISSUE THREAD

**Issue by ExoticMudkipz** [TheDrawingCoder-Gamer/Funkin#85]
While I wait for my first question to be answered, I have another one that's just as important. The modifiers and victory menu kinda ruin the illusion of it being the base game. Anywhere I can edit the code so those screens don't appear?

**Comment by BetaBits** [comment]
you can disable them in options

**Comment by ExoticMudkipz** [comment]
> you can disable them in options

Is there any way to edit in a file so that it never appears? Im going to use the executable as the mod im making itself and the modifiers ruin the vibe for me. I want it so a fresh download has it so it never appears.

**Comment by MarioLuigi124** [comment]
> Is there any way to edit in a file so that it never appears? Im going to use the executable as the mod im making itself and the modifiers ruin the vibe for me. I want it so a fresh download has it so it never appears.

no

**Comment by ExoticMudkipz** [comment]
> no
Aight. Hopefully it comes as a feature soon enough where you can edit a json and disable them from appearing.

**Comment by MarioLuigi124** [comment]
options.json

**Comment by MarioLuigi124** [comment]
options
