### ISSUE TITLE
Question: how do I add custom enemy portraits?

### ISSUE THREAD

**Issue by AndreDoodles** [TheDrawingCoder-Gamer/Funkin#89]
## What is your question?
How do I add custom portraits for characters like pico on week 3? I’ve got the dialog and stuff but it always shows senpai for the portrait and I don’t know where to put my custom ones

**Comment by MasterDirector99** [comment]
Aren't you watch a tutorial? You can do the same thing as the enemy.

**Comment by AndreDoodles** [comment]
I guess I meant default enemies since I’m trying to change week 3 and the new updates got me confused without all the pings and stuff being gone

**Comment by MarioLuigi124** [comment]
you put your custom portraits in the folder of your custom character

**Comment by MrGamerDoesGames** [comment]
> you put your custom portraits files in the folder of your custom character

What do I name the portrait? Having the same question.
