### ISSUE TITLE
currently the game doesn't have a freeplaysonglist.txt

### ISSUE THREAD

**Issue by LikeToCodeStreams** [TheDrawingCoder-Gamer/Funkin#91]
its gone, i can't import custom songs. the tutorials all have it by my version doesn't. i have reinstalled it many times yet still isn't there

**Comment by MarioLuigi124** [comment]
freeplaySongJson.jsonc

**Comment by XperiorTR** [comment]
use in game character creator its easier

**Comment by MarioLuigi124** [comment]
no it's not

**Comment by MarioLuigi124** [comment]
freeplaySongJson.jsonc is the new freeplaysonglist.txt
