### ISSUE TITLE
Bug Report: Stupid portraits suck

### ISSUE THREAD

**Issue by LeonJackaman** [TheDrawingCoder-Gamer/Funkin#93]
Ok so, I'm gonna link a mediafire link of the mod, but I'm HOPING someone can help me fix this, I'm trying to make it use a portrait but it isn't working and it just shows senpai

https://www.mediafire.com/file/c48alcgdzec1ytn/help+me+;w;.rar/file

**Comment by MarioLuigi124** [comment]
the xml is going to the not existing file called ena_portrait.png you will need to move the portrait files into the ena folder in the custom characters folder and rename them to portrait (i don't how to fix the size) that is how close i'm getting...

https://user-images.githubusercontent.com/78293838/110192553-c11bfe80-7dfc-11eb-9340-82cfbb1048d6.mp4

**Comment by LeonJackaman** [comment]
That's really weird because I LITERALLY sprited it over the senpai portrait

**Comment by MarioLuigi124** [comment]
try copying the xml file for senpai's portrait

**Comment by TheDrawingCoder-Gamer** [comment]
Closing notes... If she isn't considered pixel it won't scale up the image... You have to set "isPixel" to true for it to work
