### ISSUE TITLE
Bug Report: Long Notes cuts the Vocals

### ISSUE THREAD

**Issue by GenoX-Fome** [TheDrawingCoder-Gamer/Funkin#95]
Using Windows 64 bits

I'm using the latest version (from 1 hour ago) Win640.2.7.1-mod-2.1.0

For do this is just go to any song like bopeebo and wait for a long note to play

I'm testing the original songs and my custom ones and when i press the long notes of the chart the Voices ogg glitchs/cuts and the heatlh bar counts the longs notes always as a miss

**Comment by JordanSantiagoYT** [comment]
I think you only tapped it and didn't hold it (ik this is closed)
