### ISSUE TITLE
Enhancement: Add a way to adjust the position of poses on characters

### ISSUE THREAD

**Issue by LeonJackaman** [TheDrawingCoder-Gamer/Funkin#96]
## What is your suggestion, and why should it be implemented?
 
This would be really helpful, preferably by April 2nd.

I just can't get the poses in the right place, the only way to change positions is through the game code, and you're doing that already so please ;w;

(I forgot to explain why it should be added, so here:)

Let's say my character replaces or uses the template of another character, And when you play the level, they're floating!
In that situation, imagine you could just, press like, 9 or whatever and it brings up a menu with the positions of both the player character and the enemy, and what you can do is just reposition the character or their poses wherever you want.

Idk if it's too much to ask, but it'd be really damn helpful.

**Comment by LeonJackaman** [comment]
ok so I found out about the '8' key thing, but nothing I do saves?

**Comment by TheDrawingCoder-Gamer** [comment]
have to manually edit json :heart: sorry you have to learn how to json
