### ISSUE TITLE
Custom songs bug out

### ISSUE THREAD

**Issue by Arthur-pootis** [TheDrawingCoder-Gamer/Funkin#97]
When i putted the noob beta song, the charting bugged off and the music didnt play, please help, this happens when doing it from the options tab

**Comment by Arthur-pootis** [comment]
nvm putting the .ogg's in the music folder fucks it up

**Comment by MrGamerDoesGames** [comment]
Well where else am I supposed to put them? Having the same problem here.

**Comment by IAmAHumanToo** [comment]
Literally ANYWHERE else

> Well where else am I supposed to put them? Having the same problem here.
